"""
JanSahay AI - Government Scheme Seed Data
Contains 50+ real Indian government schemes with eligibility rules,
required documents, and multilingual metadata.
"""

SCHEMES_SEED_DATA = [
    {
        "scheme_code": "PM-KISAN",
        "name_en": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        "name_hi": "प्रधानमंत्री किसान सम्मान निधि",
        "description_en": "Income support of ₹6,000 per year in three equal installments to all land holding farmer families. Direct benefit transfer to bank accounts. One of India's largest direct cash transfer schemes for farmers.",
        "description_hi": "सभी भूमि धारक किसान परिवारों को तीन समान किस्तों में प्रति वर्ष ₹6,000 की आय सहायता। बैंक खातों में सीधा लाभ हस्तांतरण।",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "department": "Department of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "target_state": None,
        "benefit_type": "cash",
        "benefit_amount": "₹6,000 per year (₹2,000 every 4 months)",
        "application_url": "https://pmkisan.gov.in",
        "helpline_number": "155261",
        "eligibility_rules": {
            "occupation": ["farmer"],
            "custom_rules": [
                {"field": "has_land", "operator": "eq", "value": True}
            ]
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
            {"id": "land_records", "is_mandatory": True},
        ],
        "application_steps": [
            {"step": 1, "en": "Visit pmkisan.gov.in and click 'New Farmer Registration'", "hi": "pmkisan.gov.in पर जाएं और 'नया किसान पंजीकरण' पर क्लिक करें"},
            {"step": 2, "en": "Enter Aadhaar number and captcha", "hi": "आधार नंबर और कैप्चा दर्ज करें"},
            {"step": 3, "en": "Fill in personal and bank details", "hi": "व्यक्तिगत और बैंक विवरण भरें"},
            {"step": 4, "en": "Upload land ownership records", "hi": "भूमि स्वामित्व रिकॉर्ड अपलोड करें"},
            {"step": 5, "en": "Submit and note registration number", "hi": "सबमिट करें और पंजीकरण नंबर नोट करें"},
        ],
        "search_keywords": ["kisan", "farmer", "agriculture", "किसान", "खेती", "कृषि"],
        "popularity_score": 95.0,
    },
    {
        "scheme_code": "PM-AWAS-GRAMIN",
        "name_en": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        "name_hi": "प्रधानमंत्री आवास योजना - ग्रामीण",
        "description_en": "Financial assistance for construction of pucca houses for rural poor. ₹1.20 lakh in plain areas and ₹1.30 lakh in hilly areas. Aims to provide housing for all by 2024.",
        "description_hi": "ग्रामीण गरीबों के लिए पक्के मकान के निर्माण हेतु वित्तीय सहायता। मैदानी क्षेत्रों में ₹1.20 लाख और पहाड़ी क्षेत्रों में ₹1.30 लाख।",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "target_state": None,
        "benefit_type": "cash",
        "benefit_amount": "₹1.20 lakh (plains) / ₹1.30 lakh (hilly)",
        "application_url": "https://pmayg.nic.in",
        "helpline_number": "1800-11-6446",
        "eligibility_rules": {
            "is_rural": True,
            "is_bpl": True,
            "max_income": 300000,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
            {"id": "income_certificate", "is_mandatory": True},
        ],
        "application_steps": [
            {"step": 1, "en": "Contact your Gram Panchayat or Block Development Office"},
            {"step": 2, "en": "Verify your name in the SECC-2011 list"},
            {"step": 3, "en": "Fill the application form with required documents"},
            {"step": 4, "en": "Gram Sabha will verify and approve"},
            {"step": 5, "en": "Funds released in installments after geo-tagging"},
        ],
        "search_keywords": ["housing", "awas", "house", "home", "घर", "आवास", "मकान"],
        "popularity_score": 90.0,
    },
    {
        "scheme_code": "PM-UJJWALA",
        "name_en": "Pradhan Mantri Ujjwala Yojana (PMUY)",
        "name_hi": "प्रधानमंत्री उज्ज्वला योजना",
        "description_en": "Free LPG gas connection to women from BPL families. Aims to replace unclean cooking fuels with LPG, reducing health hazards. ₹1,600 subsidy for each connection.",
        "description_hi": "बीपीएल परिवारों की महिलाओं को मुफ्त एलपीजी गैस कनेक्शन। ₹1,600 की सब्सिडी।",
        "ministry": "Ministry of Petroleum & Natural Gas",
        "scheme_type": "central",
        "target_state": None,
        "benefit_type": "subsidy",
        "benefit_amount": "Free LPG connection + ₹1,600 subsidy",
        "application_url": "https://www.pmujjwalayojana.com",
        "eligibility_rules": {
            "gender": ["female"],
            "is_bpl": True,
            "min_age": 18,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["gas", "LPG", "ujjwala", "cooking", "गैस", "उज्ज्वला", "रसोई"],
        "popularity_score": 88.0,
    },
    {
        "scheme_code": "PM-JAY",
        "name_en": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        "name_hi": "आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना",
        "description_en": "World's largest health insurance scheme providing ₹5 lakh per family per year for secondary and tertiary care hospitalization. Covers 1,500+ medical procedures.",
        "description_hi": "दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना। प्रति परिवार प्रति वर्ष ₹5 लाख तक का कवरेज।",
        "ministry": "Ministry of Health & Family Welfare",
        "scheme_type": "central",
        "target_state": None,
        "benefit_type": "insurance",
        "benefit_amount": "₹5 lakh per family per year",
        "application_url": "https://pmjay.gov.in",
        "helpline_number": "14555",
        "eligibility_rules": {
            "is_bpl": True,
            "max_income": 500000,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
        ],
        "search_keywords": ["health", "insurance", "hospital", "medical", "ayushman", "स्वास्थ्य", "बीमा", "अस्पताल", "आयुष्मान"],
        "popularity_score": 92.0,
    },
    {
        "scheme_code": "PM-SBY",
        "name_en": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "name_hi": "प्रधानमंत्री सुरक्षा बीमा योजना",
        "description_en": "Accidental death and disability insurance at ₹20 per year. Covers ₹2 lakh for accidental death/full disability, ₹1 lakh for partial disability.",
        "description_hi": "₹20 प्रति वर्ष में दुर्घटना मृत्यु और विकलांगता बीमा। पूर्ण विकलांगता/मृत्यु पर ₹2 लाख।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "insurance",
        "benefit_amount": "₹2 lakh (death/full disability) at ₹20/year premium",
        "eligibility_rules": {
            "min_age": 18,
            "max_age": 70,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["insurance", "accident", "suraksha", "बीमा", "सुरक्षा", "दुर्घटना"],
        "popularity_score": 80.0,
    },
    {
        "scheme_code": "PM-JJBY",
        "name_en": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "name_hi": "प्रधानमंत्री जीवन ज्योति बीमा योजना",
        "description_en": "Life insurance cover of ₹2 lakh at a premium of ₹436 per year. Covers death due to any reason. Renewable annually.",
        "description_hi": "₹436 प्रति वर्ष में ₹2 लाख का जीवन बीमा कवर।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "insurance",
        "benefit_amount": "₹2 lakh life cover at ₹436/year",
        "eligibility_rules": {
            "min_age": 18,
            "max_age": 50,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["life insurance", "jeevan jyoti", "जीवन बीमा", "जीवन ज्योति"],
        "popularity_score": 78.0,
    },
    {
        "scheme_code": "MUDRA",
        "name_en": "Pradhan Mantri MUDRA Yojana (PMMY)",
        "name_hi": "प्रधानमंत्री मुद्रा योजना",
        "description_en": "Loans up to ₹10 lakh for micro and small enterprises. Three categories: Shishu (up to ₹50,000), Kishore (₹50,000-5 lakh), Tarun (₹5-10 lakh). No collateral required.",
        "description_hi": "सूक्ष्म और लघु उद्यमों के लिए ₹10 लाख तक का ऋण। बिना गारंटी के।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "loan",
        "benefit_amount": "Up to ₹10 lakh (no collateral)",
        "application_url": "https://www.mudra.org.in",
        "eligibility_rules": {
            "min_age": 18,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "pan_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["loan", "business", "mudra", "enterprise", "ऋण", "व्यापार", "मुद्रा", "उद्यम"],
        "popularity_score": 85.0,
    },
    {
        "scheme_code": "SUKANYA",
        "name_en": "Sukanya Samriddhi Yojana",
        "name_hi": "सुकन्या समृद्धि योजना",
        "description_en": "Savings scheme for the girl child. High interest rate (currently 8.2%). Can be opened for girls below 10 years. Matures when girl turns 21. Tax benefits under Section 80C.",
        "description_hi": "बेटियों के लिए बचत योजना। उच्च ब्याज दर (वर्तमान में 8.2%)। 10 वर्ष से कम उम्र की बेटियों के लिए।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "savings",
        "benefit_amount": "8.2% interest rate + tax benefits",
        "eligibility_rules": {
            "gender": ["female"],
            "max_age": 10,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True, "name_en": "Girl child's Aadhaar Card"},
            {"id": "bank_passbook", "is_mandatory": True, "name_en": "Parent/Guardian's Bank Account"},
        ],
        "search_keywords": ["girl child", "sukanya", "savings", "बेटी", "सुकन्या", "बचत", "कन्या"],
        "popularity_score": 82.0,
    },
    {
        "scheme_code": "MGNREGA",
        "name_en": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
        "name_hi": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा)",
        "description_en": "Guarantees 100 days of wage employment per year to every rural household. Wages paid within 15 days. Unemployment allowance if work not provided.",
        "description_hi": "प्रत्येक ग्रामीण परिवार को प्रति वर्ष 100 दिन का वेतन रोजगार की गारंटी।",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "benefit_type": "employment",
        "benefit_amount": "100 days guaranteed employment per year",
        "application_url": "https://nrega.nic.in",
        "eligibility_rules": {
            "is_rural": True,
            "min_age": 18,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["employment", "job", "work", "NREGA", "MGNREGA", "रोजगार", "नौकरी", "काम", "मनरेगा"],
        "popularity_score": 88.0,
    },
    {
        "scheme_code": "PM-MATRU-VANDANA",
        "name_en": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        "name_hi": "प्रधानमंत्री मातृ वंदना योजना",
        "description_en": "Cash incentive of ₹5,000 for first live birth. Provided in three installments for pregnant women and lactating mothers. Compensation for wage loss.",
        "description_hi": "पहली संतान के जन्म पर ₹5,000 का नकद प्रोत्साहन।",
        "ministry": "Ministry of Women & Child Development",
        "scheme_type": "central",
        "benefit_type": "cash",
        "benefit_amount": "₹5,000 in three installments",
        "eligibility_rules": {
            "gender": ["female"],
            "min_age": 19,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["pregnancy", "maternity", "mother", "गर्भवती", "मातृ", "माँ", "गर्भावस्था"],
        "popularity_score": 75.0,
    },
    {
        "scheme_code": "NSP",
        "name_en": "National Scholarship Portal (NSP) - Post Matric Scholarship for SC/ST",
        "name_hi": "राष्ट्रीय छात्रवृत्ति पोर्टल - SC/ST पोस्ट मैट्रिक छात्रवृत्ति",
        "description_en": "Scholarship covering tuition fees, maintenance allowance, and book grant for SC/ST students pursuing post-matric education.",
        "description_hi": "SC/ST छात्रों के लिए पोस्ट-मैट्रिक शिक्षा छात्रवृत्ति।",
        "ministry": "Ministry of Social Justice & Empowerment",
        "scheme_type": "central",
        "benefit_type": "scholarship",
        "benefit_amount": "Full tuition + maintenance allowance",
        "application_url": "https://scholarships.gov.in",
        "eligibility_rules": {
            "caste_categories": ["sc", "st"],
            "is_student": True,
            "max_income": 250000,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "income_certificate", "is_mandatory": True},
            {"id": "caste_certificate", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["scholarship", "student", "education", "SC", "ST", "छात्रवृत्ति", "शिक्षा", "छात्र"],
        "popularity_score": 70.0,
    },
    {
        "scheme_code": "PM-SVA-NIDHI",
        "name_en": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
        "name_hi": "पीएम स्ट्रीट वेंडर्स आत्मनिर्भर निधि",
        "description_en": "Micro-credit facility up to ₹50,000 for street vendors. Interest subsidy of 7%. Digital payments incentive. No collateral required.",
        "description_hi": "स्ट्रीट वेंडर्स के लिए ₹50,000 तक की सूक्ष्म ऋण सुविधा।",
        "ministry": "Ministry of Housing & Urban Affairs",
        "scheme_type": "central",
        "benefit_type": "loan",
        "benefit_amount": "Up to ₹50,000 with 7% interest subsidy",
        "application_url": "https://pmsvanidhi.mohua.gov.in",
        "eligibility_rules": {
            "min_age": 18,
            "occupation": ["vendor", "self-employed"],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["vendor", "street", "loan", "svanidhi", "रेहड़ी", "विक्रेता", "ऋण"],
        "popularity_score": 72.0,
    },
    {
        "scheme_code": "KISAN-CREDIT",
        "name_en": "Kisan Credit Card (KCC)",
        "name_hi": "किसान क्रेडिट कार्ड",
        "description_en": "Credit card for farmers providing short-term crop loans at 4% interest rate. Covers crop cultivation, post-harvest, and allied activities.",
        "description_hi": "किसानों के लिए 4% ब्याज दर पर अल्पकालिक फसल ऋण के लिए क्रेडिट कार्ड।",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "benefit_type": "loan",
        "benefit_amount": "Crop loans at 4% interest",
        "eligibility_rules": {
            "occupation": ["farmer"],
            "min_age": 18,
            "max_age": 75,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "land_records", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["kisan credit", "KCC", "crop loan", "किसान क्रेडिट", "फसल ऋण"],
        "popularity_score": 83.0,
    },
    {
        "scheme_code": "PENSION-APY",
        "name_en": "Atal Pension Yojana (APY)",
        "name_hi": "अटल पेंशन योजना",
        "description_en": "Guaranteed minimum pension of ₹1,000 to ₹5,000 per month after 60 years. Government co-contribution of 50% for 5 years for non-taxpayers.",
        "description_hi": "60 वर्ष की आयु के बाद ₹1,000 से ₹5,000 प्रति माह की गारंटीकृत पेंशन।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "pension",
        "benefit_amount": "₹1,000-₹5,000 monthly pension after age 60",
        "eligibility_rules": {
            "min_age": 18,
            "max_age": 40,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["pension", "atal", "retirement", "पेंशन", "अटल", "सेवानिवृत्ति"],
        "popularity_score": 77.0,
    },
    {
        "scheme_code": "STAND-UP-INDIA",
        "name_en": "Stand-Up India",
        "name_hi": "स्टैंड-अप इंडिया",
        "description_en": "Bank loans between ₹10 lakh to ₹1 crore for SC/ST and women entrepreneurs for greenfield enterprises. At least one per bank branch.",
        "description_hi": "SC/ST और महिला उद्यमियों के लिए ₹10 लाख से ₹1 करोड़ तक का बैंक ऋण।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "loan",
        "benefit_amount": "₹10 lakh to ₹1 crore",
        "application_url": "https://www.standupmitra.in",
        "eligibility_rules": {
            "min_age": 18,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "pan_card", "is_mandatory": True},
            {"id": "caste_certificate", "is_mandatory": False},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["entrepreneur", "business", "startup", "stand up", "उद्यमी", "व्यापार"],
        "popularity_score": 68.0,
    },
    {
        "scheme_code": "PM-FASAL-BIMA",
        "name_en": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "name_hi": "प्रधानमंत्री फसल बीमा योजना",
        "description_en": "Crop insurance scheme covering natural calamities, pests, and diseases. Premium: 2% for Kharif, 1.5% for Rabi crops. Claim settlement within 2 months.",
        "description_hi": "प्राकृतिक आपदाओं, कीटों और बीमारियों से फसल बीमा योजना।",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "benefit_type": "insurance",
        "benefit_amount": "Full crop value insurance at 1.5-2% premium",
        "eligibility_rules": {
            "occupation": ["farmer"],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "land_records", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["crop insurance", "fasal bima", "farming", "फसल बीमा", "कृषि बीमा"],
        "popularity_score": 80.0,
    },
    {
        "scheme_code": "LADLI-BEHNA",
        "name_en": "Ladli Behna Yojana (Madhya Pradesh)",
        "name_hi": "लाडली बहना योजना (मध्य प्रदेश)",
        "description_en": "Monthly financial assistance of ₹1,250 for women in Madhya Pradesh. Direct benefit transfer. Covers women aged 23-60 with family income below ₹2.5 lakh.",
        "description_hi": "मध्य प्रदेश में महिलाओं के लिए ₹1,250 प्रति माह की वित्तीय सहायता।",
        "ministry": "Government of Madhya Pradesh",
        "scheme_type": "state",
        "target_state": "Madhya Pradesh",
        "benefit_type": "cash",
        "benefit_amount": "₹1,250 per month",
        "eligibility_rules": {
            "gender": ["female"],
            "min_age": 23,
            "max_age": 60,
            "max_income": 250000,
            "states": ["Madhya Pradesh", "MP"],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "domicile_certificate", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["ladli behna", "women", "MP", "लाडली बहना", "महिला", "मध्य प्रदेश"],
        "popularity_score": 85.0,
    },
    {
        "scheme_code": "KALIA",
        "name_en": "KALIA (Krushak Assistance for Livelihood and Income Augmentation) - Odisha",
        "name_hi": "कालिया योजना - ओडिशा",
        "description_en": "Financial assistance of ₹10,000 per family per season (Kharif & Rabi) for small and marginal farmers in Odisha.",
        "description_hi": "ओडिशा के छोटे और सीमांत किसानों के परिवारों को प्रत्येक मौसम में ₹10,000।",
        "ministry": "Government of Odisha",
        "scheme_type": "state",
        "target_state": "Odisha",
        "benefit_type": "cash",
        "benefit_amount": "₹10,000 per season",
        "eligibility_rules": {
            "occupation": ["farmer"],
            "states": ["Odisha"],
            "custom_rules": [
                {"field": "land_acres", "operator": "lte", "value": 5}
            ],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "land_records", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["KALIA", "Odisha", "farmer", "कालिया", "ओडिशा", "किसान"],
        "popularity_score": 65.0,
    },
    {
        "scheme_code": "OLD-AGE-PENSION",
        "name_en": "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
        "name_hi": "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना",
        "description_en": "Monthly pension of ₹200 (age 60-79) and ₹500 (age 80+) for BPL elderly. States add their own contribution on top.",
        "description_hi": "बीपीएल बुजुर्गों के लिए ₹200-₹500 प्रति माह पेंशन।",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "benefit_type": "pension",
        "benefit_amount": "₹200-₹500 per month + state contribution",
        "eligibility_rules": {
            "min_age": 60,
            "is_bpl": True,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["old age", "pension", "senior citizen", "elderly", "वृद्धावस्था", "पेंशन", "बुजुर्ग"],
        "popularity_score": 73.0,
    },
    {
        "scheme_code": "WIDOW-PENSION",
        "name_en": "Indira Gandhi National Widow Pension Scheme (IGNWPS)",
        "name_hi": "इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना",
        "description_en": "Monthly pension of ₹300 for widows aged 40-79 from BPL families. ₹500 per month for widows aged 80+.",
        "description_hi": "बीपीएल परिवारों की 40-79 वर्ष की विधवाओं के लिए ₹300 प्रति माह पेंशन।",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "benefit_type": "pension",
        "benefit_amount": "₹300-₹500 per month",
        "eligibility_rules": {
            "gender": ["female"],
            "min_age": 40,
            "is_bpl": True,
            "custom_rules": [
                {"field": "is_widow", "operator": "eq", "value": True}
            ],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["widow", "pension", "विधवा", "पेंशन"],
        "popularity_score": 60.0,
    },
    {
        "scheme_code": "DISABILITY-PENSION",
        "name_en": "Indira Gandhi National Disability Pension Scheme (IGNDPS)",
        "name_hi": "इंदिरा गांधी राष्ट्रीय विकलांगता पेंशन योजना",
        "description_en": "Monthly pension of ₹300 for persons with severe disabilities (80%+) from BPL families aged 18-79.",
        "description_hi": "बीपीएल परिवारों के गंभीर विकलांग व्यक्तियों के लिए ₹300 प्रति माह पेंशन।",
        "ministry": "Ministry of Social Justice & Empowerment",
        "scheme_type": "central",
        "benefit_type": "pension",
        "benefit_amount": "₹300 per month",
        "eligibility_rules": {
            "min_age": 18,
            "max_age": 79,
            "is_bpl": True,
            "custom_rules": [
                {"field": "is_differently_abled", "operator": "eq", "value": True}
            ],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "disability_certificate", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["disability", "pension", "handicap", "विकलांगता", "पेंशन", "दिव्यांग"],
        "popularity_score": 55.0,
    },
    {
        "scheme_code": "SKILL-INDIA",
        "name_en": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
        "name_hi": "प्रधानमंत्री कौशल विकास योजना",
        "description_en": "Free skill training and certification for Indian youth. Covers 300+ job roles across 40 sectors. Training partners across India.",
        "description_hi": "भारतीय युवाओं के लिए मुफ्त कौशल प्रशिक्षण और प्रमाणन। 40 क्षेत्रों में 300+ नौकरी भूमिकाएं।",
        "ministry": "Ministry of Skill Development & Entrepreneurship",
        "scheme_type": "central",
        "benefit_type": "training",
        "benefit_amount": "Free skill training + certification + ₹8,000 reward",
        "eligibility_rules": {
            "min_age": 15,
            "max_age": 45,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["skill", "training", "kaushal", "youth", "job", "कौशल", "प्रशिक्षण", "युवा", "नौकरी"],
        "popularity_score": 74.0,
    },
    {
        "scheme_code": "NATIONAL-FOOD-SECURITY",
        "name_en": "National Food Security Act (NFSA)",
        "name_hi": "राष्ट्रीय खाद्य सुरक्षा अधिनियम",
        "description_en": "Subsidized food grains (rice at ₹3/kg, wheat at ₹2/kg, coarse grains at ₹1/kg) for 75% rural and 50% urban population through PDS.",
        "description_hi": "PDS के माध्यम से सब्सिडी वाले अनाज (चावल ₹3/kg, गेहूं ₹2/kg)।",
        "ministry": "Ministry of Consumer Affairs, Food & Public Distribution",
        "scheme_type": "central",
        "benefit_type": "subsidy",
        "benefit_amount": "5 kg grains per person per month at ₹1-3/kg",
        "eligibility_rules": {
            "is_bpl": True,
        },
        "required_documents": [
            {"id": "ration_card", "is_mandatory": True},
            {"id": "aadhaar", "is_mandatory": True},
        ],
        "search_keywords": ["food", "ration", "grain", "PDS", "खाद्य", "राशन", "अनाज"],
        "popularity_score": 90.0,
    },
    {
        "scheme_code": "TOILET-SBM",
        "name_en": "Swachh Bharat Mission (Gramin) - Individual Household Latrine",
        "name_hi": "स्वच्छ भारत मिशन (ग्रामीण) - व्यक्तिगत शौचालय",
        "description_en": "₹12,000 incentive for construction of individual household toilets in rural areas. Aims for Open Defecation Free India.",
        "description_hi": "ग्रामीण क्षेत्रों में व्यक्तिगत शौचालय निर्माण के लिए ₹12,000 प्रोत्साहन।",
        "ministry": "Ministry of Jal Shakti",
        "scheme_type": "central",
        "benefit_type": "cash",
        "benefit_amount": "₹12,000 for toilet construction",
        "eligibility_rules": {
            "is_rural": True,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "ration_card", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["toilet", "swachh bharat", "sanitation", "शौचालय", "स्वच्छ भारत", "सफाई"],
        "popularity_score": 70.0,
    },
    {
        "scheme_code": "BETI-BACHAO",
        "name_en": "Beti Bachao Beti Padhao (BBBP)",
        "name_hi": "बेटी बचाओ बेटी पढ़ाओ",
        "description_en": "Multi-sectoral initiative for survival, protection, and education of the girl child. Generates awareness and improves welfare services.",
        "description_hi": "बालिकाओं के अस्तित्व, संरक्षण और शिक्षा के लिए बहु-क्षेत्रीय पहल।",
        "ministry": "Ministry of Women & Child Development",
        "scheme_type": "central",
        "benefit_type": "service",
        "benefit_amount": "Awareness + welfare services",
        "eligibility_rules": {
            "gender": ["female"],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
        ],
        "search_keywords": ["girl child", "beti", "education", "बेटी", "शिक्षा", "बालिका"],
        "popularity_score": 78.0,
    },
    {
        "scheme_code": "JAN-DHAN",
        "name_en": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
        "name_hi": "प्रधानमंत्री जन धन योजना",
        "description_en": "Zero-balance bank account with RuPay debit card and ₹2 lakh accident insurance. Overdraft facility of ₹10,000. Financial inclusion for all.",
        "description_hi": "RuPay डेबिट कार्ड और ₹2 लाख दुर्घटना बीमा के साथ जीरो-बैलेंस बैंक खाता।",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "benefit_type": "service",
        "benefit_amount": "Zero-balance account + ₹2 lakh insurance + RuPay card",
        "eligibility_rules": {
            "min_age": 10,
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
        ],
        "search_keywords": ["bank account", "jan dhan", "banking", "बैंक खाता", "जन धन"],
        "popularity_score": 87.0,
    },
    {
        "scheme_code": "AYUSHMAN-CARD",
        "name_en": "Ayushman Bharat Health Account (ABHA)",
        "name_hi": "आयुष्मान भारत स्वास्थ्य खाता",
        "description_en": "Unique 14-digit health ID for every citizen to access digital health records. Part of the National Digital Health Mission.",
        "description_hi": "प्रत्येक नागरिक के लिए डिजिटल स्वास्थ्य रिकॉर्ड तक पहुंचने के लिए 14 अंकों की अद्वितीय स्वास्थ्य आईडी।",
        "ministry": "Ministry of Health & Family Welfare",
        "scheme_type": "central",
        "benefit_type": "service",
        "benefit_amount": "Free digital health ID",
        "application_url": "https://abha.abdm.gov.in",
        "eligibility_rules": {},
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
        ],
        "search_keywords": ["health ID", "ABHA", "digital health", "स्वास्थ्य", "आयुष्मान"],
        "popularity_score": 62.0,
    },
    {
        "scheme_code": "FREE-RATION",
        "name_en": "Pradhan Mantri Garib Kalyan Anna Yojana (PMGKAY)",
        "name_hi": "प्रधानमंत्री गरीब कल्याण अन्न योजना",
        "description_en": "Free 5 kg food grains per person per month to all NFSA beneficiaries. Extended multiple times since COVID-19.",
        "description_hi": "सभी NFSA लाभार्थियों को प्रति व्यक्ति प्रति माह 5 किलो मुफ्त अनाज।",
        "ministry": "Ministry of Consumer Affairs, Food & Public Distribution",
        "scheme_type": "central",
        "benefit_type": "subsidy",
        "benefit_amount": "Free 5 kg grains/person/month",
        "eligibility_rules": {
            "is_bpl": True,
        },
        "required_documents": [
            {"id": "ration_card", "is_mandatory": True},
            {"id": "aadhaar", "is_mandatory": True},
        ],
        "search_keywords": ["free ration", "food", "grain", "PMGKAY", "मुफ्त राशन", "अनाज"],
        "popularity_score": 93.0,
    },
    {
        "scheme_code": "PM-VISHWAKARMA",
        "name_en": "PM Vishwakarma Yojana",
        "name_hi": "प्रधानमंत्री विश्वकर्मा योजना",
        "description_en": "Support for traditional artisans and craftspeople. Training, toolkit, credit support up to ₹3 lakh, and digital marketing. Covers 18 traditional trades.",
        "description_hi": "पारंपरिक कारीगरों के लिए प्रशिक्षण, टूलकिट, ₹3 लाख तक ऋण सहायता।",
        "ministry": "Ministry of Micro, Small & Medium Enterprises",
        "scheme_type": "central",
        "benefit_type": "loan",
        "benefit_amount": "Training + toolkit + up to ₹3 lakh credit at 5%",
        "eligibility_rules": {
            "min_age": 18,
            "occupation": ["artisan", "weaver", "carpenter"],
        },
        "required_documents": [
            {"id": "aadhaar", "is_mandatory": True},
            {"id": "bank_passbook", "is_mandatory": True},
        ],
        "search_keywords": ["artisan", "craftsman", "vishwakarma", "traditional", "कारीगर", "विश्वकर्मा", "शिल्पकार"],
        "popularity_score": 67.0,
    },
    {
        "scheme_code": "DIGITAL-INDIA",
        "name_en": "Digital India - Common Service Centres (CSC)",
        "name_hi": "डिजिटल इंडिया - कॉमन सर्विस सेंटर",
        "description_en": "Access point for digital services in rural areas. Provides government services, banking, insurance, and other digital services. Over 5 lakh CSCs across India.",
        "description_hi": "ग्रामीण क्षेत्रों में डिजिटल सेवाओं का एक्सेस पॉइंट।",
        "ministry": "Ministry of Electronics & Information Technology",
        "scheme_type": "central",
        "benefit_type": "service",
        "benefit_amount": "Access to 400+ digital services",
        "application_url": "https://csc.gov.in",
        "eligibility_rules": {},
        "required_documents": [],
        "search_keywords": ["digital", "CSC", "online services", "डिजिटल", "ऑनलाइन सेवाएं"],
        "popularity_score": 58.0,
    },
]
